### PR TITLE
require ruby verions 2.1 or greater

### PR DESCRIPTION
**Pull request by mejackreed**

### CODE REVIEW

**Comment by jkeck** [comment]
Is this ready to :ship:? I can't remember what the impetus for pinning to 2.1 was.

**Comment by mejackreed** [comment]
Yeah I say :shipit: ... named parameters here: https://github.com/sul-dlss/sul_styles/blob/master/lib/sul_styles/colors.rb#L59

Caused some issues when @aeschylus was installing locally using Ruby 2.0 (default OSX). Though looking into it more it seems liked named params were introduced in 2.0. Thoughts?

**Comment by cbeer** [comment]
Named parameters were introduced in 2.0, but required name parameters were only added in 2.1.

**Comment by mejackreed** [comment]
Thanks @cbeer ! :shipit:

**Comment by jkeck** [comment]
Should we not use the required named params then (do we have any less than ruby 2.1 app that may want to use this, or should we tell them they should upgrade)?

And btw, I guess that was my bad, since I added that method. :fearful:

**Comment by jkeck** [comment]
I'm thinking argo/hydrus, which appear to be 1.9.3 actually. :frowning:

**Comment by cbeer** [comment]
If argo/hydrus ever need to use `sul_styles` before they can get upgraded to maintained dependencies, we could relax the dependency then (although I suspect they won't need it in the near term...)

**Comment by mejackreed** [comment]
IDK... @atz @jmartin-sul .. there is this: 

https://github.com/sul-dlss/argo/commit/a7b8efc941283429a47b3ee5ebc6b9793909e08f

**Comment by mejackreed** [comment]
Also this: https://github.com/sul-dlss/argo/blob/develop/.travis.yml#L3 I wonder if support is coming?

**Comment by jkeck** [comment]
@atz was asking about it recently I think (well, was asking what should be used instead of SUL-Chrome), which is why I ask.  But agreed, it will be easy enough for use to change that then anyway. I'm going to :shipit: but @atz and @jmartin-sul should feel free to chime in here if they feel strongly that we should relax the dependency.

**Comment by jmartin-sul** [comment]
@mejackreed @jkeck @atz 

the intention is to move argo to the latest version of ruby as soon as the blacklight upgrade is done, so i think we're fine pinning to an old version of sul_styles for now, unless there's some big downside to that which i'm unaware of.  i wouldn't jump through any hoops to relax the ruby requirement for sul_styles.

**Pull request merged**
